name = "SimplicialCubature"
uuid = "552d7cc9-94b7-4d62-a95c-872e87830e46"
authors = ["Stéphane Laurent <laurent_step@outlook.fr>"]
version = "0.2.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
TypedPolynomials = "afbbf031-7a57-5f58-a1b9-b774a0fad08d"

[compat]
TypedPolynomials = "0.3"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
